### ISSUE TITLE
Generate crashes with Empty enum msg

### ISSUE THREAD

**Issue by de-husk** [CosmWasm/cosmwasm-typescript-gen#27]
Having an empty `QueryMsg` enum: 
```
pub enum QueryMsg {}
```
https://github.com/DA0-DA0/dao-contracts/pull/370/files#diff-840200e9bacf09b0b4728e7462feae7f2bd9cfbc92ae5d3cfe330c1a47b0ff9cR22

Causes an error when generating the ts files:
```
SyntaxError: '=>' expected. (9:1)
  7 |
  8 | export type QueryMsg = ()
> 9 |
    | ^
    at Ve (/home/runner/work/dao-contracts/dao-contracts/types/node_modules/json-schema-to-typescript/node_modules/prettier/parser-typescript.js:1:[15](https://github.com/DA0-DA0/dao-contracts/runs/7050221031?check_suite_focus=true#step:5:16)607)
    at vz (/home/runner/work/dao-contracts/dao-contracts/types/node_modules/json-schema-to-typescript/node_modules/prettier/parser-typescript.js:280:5919)
    at Object.yz [as parse] (/home/runner/work/dao-contracts/dao-contracts/types/node_modules/json-schema-to-typescript/node_modules/prettier/parser-typescript.js:280:6242)
    at Object.parse (/home/runner/work/dao-contracts/dao-contracts/types/node_modules/json-schema-to-typescript/node_modules/prettier/index.js:7334:23)
    at coreFormat (/home/runner/work/dao-contracts/dao-contracts/types/node_modules/json-schema-to-typescript/node_modules/prettier/index.js:8645:18)
    at formatWithCursor2 (/home/runner/work/dao-contracts/dao-contracts/types/node_modules/json-schema-to-typescript/node_modules/prettier/index.js:8837:18)
    at /home/runner/work/dao-contracts/dao-contracts/types/node_modules/json-schema-to-typescript/node_modules/prettier/index.js:37226:12
    at Object.format (/home/runner/work/dao-contracts/dao-contracts/types/node_modules/json-schema-to-typescript/node_modules/prettier/index.js:37240:12)
    at Object.format (/home/runner/work/dao-contracts/dao-contracts/types/node_modules/json-schema-to-typescript/dist/src/formatter.js:20:23)
    at /home/runner/work/dao-contracts/dao-contracts/types/node_modules/json-schema-to-typescript/dist/src/index.js:[17](https://github.com/DA0-DA0/dao-contracts/runs/7050221031?check_suite_focus=true#step:5:18)0:45 {
  loc: { start: { line: 9, column: 1 } },
  codeFrame: '  7 |\n  8 | export type QueryMsg = ()\n> 9 |\n    | ^'
}
```
https://github.com/DA0-DA0/dao-contracts/runs/7050221031?check_suite_focus=true#step:5:14

The json schema when exporting an empty enum: 
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "QueryMsg",
  "type": "string",
  "enum": []
}
```

**Comment by pyramation** [comment]
Thanks for reporting! Will get this ASAP

tracking here https://github.com/CosmWasm/cosmwasm-typescript-gen/tree/fix/empty-enums

**Comment by pyramation** [comment]
ok, so I've discovered this is an error in a dependency. Will be pushing upstream.
https://github.com/bcherny/json-schema-to-typescript/issues/463

**Comment by pyramation** [comment]
Until either they fix the issue or we write our own processor (#7), It looks like we can delete the empty enums, or potentially look for these and pre-process JSON schema files and potentially see what modifications we need to make. 

A temporary solution:

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "QueryMsg",
  "type": "string",
  "enum": []
}
```

will compile with a change to 

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "QueryMsg",
  "type": "string"
}
```

**Comment by pyramation** [comment]
@de-husk 

```
npm install -g cosmwasm-typescript-gen@0.3.6
```

**Comment by de-husk** [comment]
Thanks again for the quick fix!
